export * from './align.type';
export * from './aside.type';
export * from './color.type';
export * from './input.type';
export * from './input-form.type';
export * from './position.type';
export * from './size.type';
export * from './svg-icon.type';
export * from './text.type';
